### ISSUE TITLE
Práctica de Visualización de Datos

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-topicos-as#1]
[Practica de cosulta de datos en Visual.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-topicos-as/files/8799946/Practica.de.cosulta.de.datos.en.Visual.pdf)

**Comment by RaelRGB** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
